### ISSUE TITLE
PowerAssertionsSupport.expect 内に複数のアサーションを書くと最後以外のアサーションのエラーが検知できません

### ISSUE THREAD

**Issue by negokaz** [lerna-stack/lerna-app-library#50]
## 対象バージョン

`2.0.0`

## 詳細

次のテストは 1 つめのアサーション `"1" === "2"` でテストが失敗することを期待しますが、実際にはテストが成功します。

```scala
    "複数項目チェックする場合" in {
      expect {
        "1" === "2"
        "2" === "2"
      }
    }
```

一方で、次のように最後のアサーションが失敗するようにすると、期待通りテストが失敗します。

```scala
    "複数項目チェックする場合" in {
      expect {
        "1" === "1"
        "1" === "2"
      }
    }
```

しかし、このケースでもエラーメッセージが次のようになり、エラーの原因が特定しづらい問題があります。

```scala
[info] expect {
[info]        |
[info]        false
[info]   at com.eed3si9n.expecty.ExpectyBase$ExpectyListener.recordingCompleted(Expecty.scala:62)
[info]   at com.eed3si9n.expecty.ExpectyBase$ExpectyListener.recordingCompleted(Expecty.scala:24)
[info]   at com.eed3si9n.expecty.RecorderRuntime.completeRecording(RecorderRuntime.scala:46)
... 以下略 ...
```

## 回避策

`expect` 一つにつき、アサーションを一つだけ書きます。

```scala
      expect("1" === "2")
      expect("2" === "2")
```

エラーメッセージも次のようになり、エラーの原因が特定しやすくなります。

```
assertion failed 

expect("1" === "2")
       |   |
       1   false
```

## 原因の調査

軽く調べた内容を共有します。

expecty 公式の `expect` の実装が `0.14.0` から `VarargsExpecty` に変わったみたいです。

[Separated unary from varargs · eed3si9n/expecty@0076266](https://github.com/eed3si9n/expecty/commit/0076266ff136e7da0eec36194a4fac35b87c5bb0)

一方、lerna-app-library の `PowerAssertionsSupport` では `Expecty` が使われています。

> ```scala
> trait PowerAssertionsSupport {
>   val expect: Expecty = new Expecty {
>     override val failEarly: Boolean = false
>   }
> }
> ```
> **[lerna-app-library/PowerAssertionsSupport.scala at v2.0.0 · lerna-stack/lerna-app-library](https://github.com/lerna-stack/lerna-app-library/blob/v2.0.0/lerna-tests/src/main/scala/lerna/tests/PowerAssertionsSupport.scala#L9-L13)**

公式の `expect` と同じように複数のアサーションを書けるようにするためには `VarargsExpecty` を使えばよいと予想しています。

**Comment by xirc** [comment]
対象のソースコードです。

https://github.com/lerna-stack/lerna-app-library/blob/v2.0.0/lerna-tests/src/main/scala/lerna/tests/PowerAssertionsSupport.scala
https://github.com/lerna-stack/lerna-app-library/blob/v2.0.0/lerna-tests/src/test/scala/lerna/tests/LernaBaseSpecSpec.scala

`lerna-tests` はユーザには公開されていませんが、修正する価値があると思われます。
https://github.com/lerna-stack/lerna-app-library/blob/v2.0.0/build.sbt#L253-L267
